import { Tag } from './app/shared/models/Tag';
import {Food} from './app/shared/models/food';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'CN Tower',
    cookTime: '1-2 hours',
    price: 30,
    favorite: true,
    origins: ['day', 'night'], 
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['View'],
  },
  {
    id:'2',
    name: 'Ripley Aquarium',
    price: 50,
    cookTime: '2-3 hours',
    favorite: true,
    origins: ['day'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['Aquarium'],
  },
  { 
    id:'3',
    name: 'The Art Gallery of Ontario',
    price: 25,
    cookTime: '3-4 hours',
    favorite: true,
    origins: ['day'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['Museum'],
  },
  {
    id:'4',
    name: 'Kensington Market',
    price: 0,
    cookTime: '1-3 hours',
    favorite: true,
    origins: ['day'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['Free', 'Market'],
  },
  {
    id:'5',
    name: 'Yonge-Dundas Square',
    price: 0,
    cookTime: '1-2 hours',
    favorite: true,
    origins: ['day', 'night'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['Free', 'Shopping'],
  },
  {
    id:'6',
    name: 'Toronto Island',
    price: 30,
    cookTime: '3-5 hours',
    favorite: true,
    origins: ['night'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['Nature', 'View'],
  },
]

export const sample_tags:Tag[] = [
  { name: 'All', count: 6 }, 
  { name: 'Free', count: 2 },
  { name: 'Nature', count: 1 },
  { name: 'Market', count: 1 },
  { name: 'Aquarium', count: 1 },
  { name: 'Museum', count: 1 },
  { name: 'Shopping', count: 1 },
  { name: 'View', count: 2 },
]